server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - regex:

#       - json:
#           expressions:
#             stream: stream
#             timestamp: time
#             message: message
#             loggerName: loggerName
#             level: level
#             thrown:
#       - json:
#            expressions:
#              stack_message: message
#              commonElementCount: commonElementCount
#              localizedMessage: localizedMessage
#              name: name
#              extendedStackTrace: extendedStackTrace
#            source: thrown
#       - template:
#           source: output_msg
#           template: |
#             {{- if .level -}}
#               {{ .level }}, message: {{ .message }}, Logger: {{ .loggerName }}
#               {{- if .thrown -}}
#                 STACKTRACE
#                 Name: {{ .name }}, CommonElementCount: {{ .commonElementCount }}
#                 -----------------------
#                 {{ .extendedStackTrace }}
#               {{- end -}}
#             {{- else -}}
#               {{ .Entry }}
#             {{- end -}}
#       - output:
#           source: output_msg
    static_configs:
      - targets:
          - localhost
        labels:
          loggername: loggerName
          level: level
          job: varlogs
          __path__: /var/log/*log
  - job_name: containers
    static_configs:
      - targets:
          - 127.0.0.1:9323
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
